// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserGetExecutionHistoryReader is a Reader for the UserGetExecutionHistory structure.
type UserGetExecutionHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGetExecutionHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserGetExecutionHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserGetExecutionHistoryOK creates a UserGetExecutionHistoryOK with default headers values
func NewUserGetExecutionHistoryOK() *UserGetExecutionHistoryOK {
	return &UserGetExecutionHistoryOK{}
}

/*UserGetExecutionHistoryOK handles this case with default header values.

Request was successful
*/
type UserGetExecutionHistoryOK struct {
	Payload interface{}
}

func (o *UserGetExecutionHistoryOK) Error() string {
	return fmt.Sprintf("[GET /user/executionHistory][%d] userGetExecutionHistoryOK  %+v", 200, o.Payload)
}

func (o *UserGetExecutionHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
