// Code generated by go-swagger; DO NOT EDIT.

package position

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new position API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for position API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
PositionGet gets your positions

This endpoint is used for retrieving position information. The fields largely follow the [FIX spec](http://www.onixs.biz/fix-dictionary/5.0.SP2/msgType_AP_6580.html) definitions. Some selected fields are explained in more detail below.

The fields _account_, _symbol_, _currency_ are unique to each position and form its key.

* **account**: Your unique account ID.
* **symbol**: The contract for this position.
* **currency**: The margin currency for this position.
* **underlying**: Meta data of the _symbol_.
* **quoteCurrency**: Meta data of the _symbol_,  All prices are in the _quoteCurrency_
* **commission**: The maximum of the maker, taker, and settlement fee.
* **initMarginReq**: The initial margin requirement.  This will be at least the symbol's default initial maintenance margin, but can be higher if you choose lower leverage.
* **maintMarginReq**: The maintenance margin requirement.  This will be at least the symbol's default maintenance maintenance margin, but can be higher if you choose a higher risk limit.
* **riskLimit**: This is a function of your _maintMarginReq_.
* **leverage**: 1 / initMarginReq.
* **crossMargin**: True/false depending on whether you set cross margin on this position.
* **deleveragePercentile**: Indicates where your position is in the ADL queue.
* **rebalancedPnl**: The value of realised PNL that has transferred to your wallet for this position.
* **prevRebalancedPnl**: The value of realised PNL that has transferred to your wallet for this position since the position was closed.
* **currentQty**: The current position amount in contracts.
* **currentCost**: The current cost of the position in the settlement currency of the symbol (_currency_).
* **currentComm**: The current commission of the position in the settlement currency of the symbol (_currency_).
* **realisedCost**: The realised cost of this position calculated with regard to average cost accounting.
* **unrealisedCost**: _currentCost_ - _realisedCost_.
* **grossOpenCost**: The absolute value of your open orders for this symbol.
* **grossOpenPremium**: The amount your bidding above the mark price in the settlement currency of the symbol (_currency_).
* **markPrice**: The mark price of the symbol in _quoteCurrency_.
* **markValue**: The _currentQty_ at the mark price in the settlement currency of the symbol (_currency_).
* **homeNotional**: Value of position in units of _underlying_.
* **foreignNotional**: Value of position in units of _quoteCurrency_.
* **realisedPnl**: The negative of _realisedCost_.
* **unrealisedGrossPnl**: _markValue_ - _unrealisedCost_.
* **unrealisedPnl**: _unrealisedGrossPnl_.
* **liquidationPrice**: Once markPrice reaches this price, this position will be liquidated.
* **bankruptPrice**: Once markPrice reaches this price, this position will have no equity.

*/
func (a *Client) PositionGet(params *PositionGetParams, authInfo runtime.ClientAuthInfoWriter) (*PositionGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPositionGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Position.get",
		Method:             "GET",
		PathPattern:        "/position",
		ProducesMediaTypes: []string{"application/javascript", "application/json", "application/xml", "text/javascript", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PositionGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PositionGetOK), nil

}

/*
PositionIsolateMargin enables isolated margin or cross margin per position
*/
func (a *Client) PositionIsolateMargin(params *PositionIsolateMarginParams, authInfo runtime.ClientAuthInfoWriter) (*PositionIsolateMarginOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPositionIsolateMarginParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Position.isolateMargin",
		Method:             "POST",
		PathPattern:        "/position/isolate",
		ProducesMediaTypes: []string{"application/javascript", "application/json", "application/xml", "text/javascript", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PositionIsolateMarginReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PositionIsolateMarginOK), nil

}

/*
PositionTransferIsolatedMargin transfers equity in or out of a position
*/
func (a *Client) PositionTransferIsolatedMargin(params *PositionTransferIsolatedMarginParams, authInfo runtime.ClientAuthInfoWriter) (*PositionTransferIsolatedMarginOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPositionTransferIsolatedMarginParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Position.transferIsolatedMargin",
		Method:             "POST",
		PathPattern:        "/position/transferMargin",
		ProducesMediaTypes: []string{"application/javascript", "application/json", "application/xml", "text/javascript", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PositionTransferIsolatedMarginReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PositionTransferIsolatedMarginOK), nil

}

/*
PositionUpdateLeverage chooses leverage for a position
*/
func (a *Client) PositionUpdateLeverage(params *PositionUpdateLeverageParams, authInfo runtime.ClientAuthInfoWriter) (*PositionUpdateLeverageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPositionUpdateLeverageParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Position.updateLeverage",
		Method:             "POST",
		PathPattern:        "/position/leverage",
		ProducesMediaTypes: []string{"application/javascript", "application/json", "application/xml", "text/javascript", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PositionUpdateLeverageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PositionUpdateLeverageOK), nil

}

/*
PositionUpdateRiskLimit updates your risk limit
*/
func (a *Client) PositionUpdateRiskLimit(params *PositionUpdateRiskLimitParams, authInfo runtime.ClientAuthInfoWriter) (*PositionUpdateRiskLimitOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPositionUpdateRiskLimitParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Position.updateRiskLimit",
		Method:             "POST",
		PathPattern:        "/position/riskLimit",
		ProducesMediaTypes: []string{"application/javascript", "application/json", "application/xml", "text/javascript", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PositionUpdateRiskLimitReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PositionUpdateRiskLimitOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
